### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by macobo** [macobo/python-grader#12]
Ideally, this should be provided outside of this module - for example by a chroot jail in which all the execution takes place. 

Other alternatives to research, consider: codejail, AppArmor.

**Comment by gbishop** [comment]
Docker would be awesome for security. Low overhead and excellent isolation.

**Comment by macobo** [comment]
Thank you for the awesome suggestion. Implemented this as of dcdf2a53350918a2e816cd9e1ca8a6a205f7893e.
