### ISSUE TITLE
Timing issues

### ISSUE THREAD

**Issue by macobo** [macobo/python-grader#5]
Currently when writing to [SpoofedStdout](https://github.com/macobo/python-grader/blob/master/grader/execution_base.py) (in write function), we sleep to give the module time to do something and _possibly_ consume the output and do some other calculations.

This _might_ cause problems with the following tester/solution pair depending on how the wait after write is done (overly complicated example):
https://github.com/macobo/python-grader/blob/master/grader/tests/_helper_timing_module.py
https://github.com/macobo/python-grader/blob/master/grader/tests/timing_tester.py

(the assertion might be hit before the slow function finishes executing)
#### Goal

Design the IO in a way that avoids such problems in the future. More specifically, make sure that we do stuff in our test only when the users program is waiting on the io queue or is doing nothing. 

Note that the program should not fail when we do a write to stdin with nothing waiting to consume the input.

 ~~Waiting for the m.module to become available is not an appropriate solution, because functions might have input() statements in them~~. Function calls are blocking anyways and IO works differently there. See #6.

**Comment by aivarannamaa** [comment]
Isn't your `m.stdout.read()` blocking?

**Comment by macobo** [comment]
Nope. If it were, calling `read()` when there's nothing would cause an exception too early - we want to give the user feedback that we were expecting this or that but got nothing. 

Also, it might be useful to sometimes check whether the stdout is empty (though this could be done in a different way, by adding some extra function).

**Comment by macobo** [comment]
Closing this, I **_think**_ this is solved. However this will be a suspect for all future bugs until I gain more confidence.

**Comment by macobo** [comment]
Should be fixed with better IO model. Writing/reading from stdin blocks the current thread (if program has not finished executing yet).
