### ISSUE TITLE
Functions are blocking, which causes IO problems.

### ISSUE THREAD

**Issue by macobo** [macobo/python-grader#6]
After the user module has finished executing normally (thus Module.module becomes available), the test can call functions that do IO. 

Such function calls are blocking, which is good since we can check the return values. However, we lose the ability to dynamically give inputs to stdin, due to they needing to be there _before_ the function call is made..

``` python
def io_function():
    return input() + "!"
```

``` python
from grader import *

@test
def io_function_test(m):
     m.stdin.write("Hello") # we can't move this below the next call
     m.module.io_function()
     assert "Hello!" in m.stdout.read()
```

**_probably a wontfix**_

**Comment by aivarannamaa** [comment]
If you really need to give input dynamically, you could fake `sys.stdin` and arrange it in it's `readline`/`read`/`readlines`.

**Comment by aivarannamaa** [comment]
... but I can't think of exercise, where the tester can't provide all the necessary input beforehand.

**Comment by macobo** [comment]
> If you really need to give input dynamically, you could fake sys.stdin and arrange it in it's readline/read/readlines.

That's pretty much what we're doing already.

**Comment by macobo** [comment]
Closing this since we won't be fixing this. However it should be mentioned in the thesis.
